version: '3'
services: 
    app:
        container_name: tms-socket
        build: .
        restart: always
        volumes: 
            - .:/usr/src/app
            - dependencies:/usr/src/app/node_modules
        working_dir: /usr/src/app
        ports: 
            - 4001:4001



volumes: 
    dependencies: